const test = require('./docs/tutorial-basics')
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    // {
    //   type: 'category',
    //   label: '测试',
    //   link: {type: 'doc', id: 'test/README'},
    //   items: ['tutorial-basics/create-a-page', 'tutorial-basics/create-a-document'],
    // },
    test,
    {
      type: 'category',
      label: '开始',
      items: ['tutorial-extras/translate-your-site', 'tutorial-extras/manage-docs-versions'],
    },
    'intro',
  ]
};

module.exports = sidebars;
